# Generated by Django 4.2.8 on 2024-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('model_number', models.CharField(max_length=20)),
                ('nominal_voltage', models.PositiveIntegerField()),
                ('product_weight', models.PositiveIntegerField()),
                ('dimensions_l', models.PositiveIntegerField()),
                ('dimensions_b', models.PositiveIntegerField()),
                ('dimensions_w', models.PositiveIntegerField()),
                ('warranty', models.PositiveIntegerField()),
            ],
        ),
    ]
